var DestinyItemCategoryDefinition = {
	"1": {
		"itemCategoryHash": 1,
		"identifier": "CATEGORY_WEAPON",
		"visible": false,
		"title": "Weapon",
		"shortTitle": "Weapon",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 1,
		"index": 0
	},
	"2": {
		"itemCategoryHash": 2,
		"identifier": "CATEGORY_PRIMARY_WEAPON",
		"visible": false,
		"title": "Primary Weapon",
		"shortTitle": "Primary",
		"description": "Auto Rifles, Pulse Rifles, Scout Rifles and Hand Cannons",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 2,
		"index": 0
	},
	"3": {
		"itemCategoryHash": 3,
		"identifier": "CATEGORY_SPECIAL_WEAPON",
		"visible": false,
		"title": "Special Weapon",
		"shortTitle": "Special",
		"description": "Fusion Rifles, Shotguns, Sidearms and Sniper Rifles",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 3,
		"index": 0
	},
	"4": {
		"itemCategoryHash": 4,
		"identifier": "CATEGORY_HEAVY_WEAPON",
		"visible": false,
		"title": "Heavy Weapon",
		"shortTitle": "Heavy",
		"description": "Machine Guns, Rocket Launchers, and Swords",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 4,
		"index": 0
	},
	"5": {
		"itemCategoryHash": 5,
		"identifier": "CATEGORY_AUTO_RIFLE",
		"visible": false,
		"title": "Auto Rifle",
		"shortTitle": "Auto Rifle",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 5,
		"index": 0
	},
	"6": {
		"itemCategoryHash": 6,
		"identifier": "CATEGORY_HAND_CANNON",
		"visible": false,
		"title": "Hand Cannon",
		"shortTitle": "Hand Cannon",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 6,
		"index": 0
	},
	"7": {
		"itemCategoryHash": 7,
		"identifier": "CATEGORY_PULSE_RIFLE",
		"visible": false,
		"title": "Pulse Rifle",
		"shortTitle": "Pulse Rifle",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 7,
		"index": 0
	},
	"8": {
		"itemCategoryHash": 8,
		"identifier": "CATEGORY_SCOUT_RIFLE",
		"visible": false,
		"title": "Scout Rifle",
		"shortTitle": "Scout Rifle",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 8,
		"index": 0
	},
	"9": {
		"itemCategoryHash": 9,
		"identifier": "CATEGORY_FUSION_RIFLE",
		"visible": false,
		"title": "Fusion Rifle",
		"shortTitle": "Fusion Rifle",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 9,
		"index": 0
	},
	"10": {
		"itemCategoryHash": 10,
		"identifier": "CATEGORY_SNIPER_RIFLE",
		"visible": false,
		"title": "Sniper Rifle",
		"shortTitle": "Sniper Rifle",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 10,
		"index": 0
	},
	"11": {
		"itemCategoryHash": 11,
		"identifier": "CATEGORY_SHOTGUN",
		"visible": false,
		"title": "Shotgun",
		"shortTitle": "Shotgun",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 11,
		"index": 0
	},
	"12": {
		"itemCategoryHash": 12,
		"identifier": "CATEGORY_MACHINE_GUN",
		"visible": false,
		"title": "Machine Gun",
		"shortTitle": "Machine Gun",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 12,
		"index": 0
	},
	"13": {
		"itemCategoryHash": 13,
		"identifier": "CATEGORY_ROCKET_LAUNCHER",
		"visible": false,
		"title": "Rocket Launcher",
		"shortTitle": "Rocket Launcher",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 13,
		"index": 0
	},
	"14": {
		"itemCategoryHash": 14,
		"identifier": "CATEGORY_SIDEARM",
		"visible": false,
		"title": "Sidearm",
		"shortTitle": "Sidearm",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 14,
		"index": 0
	},
	"15": {
		"itemCategoryHash": 15,
		"identifier": "CATEGORY_CAMERA",
		"visible": false,
		"title": "Camera",
		"shortTitle": "Camera",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 15,
		"index": 0
	},
	"16": {
		"itemCategoryHash": 16,
		"identifier": "CATEGORY_QUEST_STEP",
		"visible": false,
		"title": "Quest Step",
		"shortTitle": "Quest Step",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 16,
		"index": 0
	},
	"17": {
		"itemCategoryHash": 17,
		"identifier": "CATEGORY_QUEST_STEP_COMPLETE",
		"visible": false,
		"title": "",
		"shortTitle": "",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 17,
		"index": 0
	},
	"18": {
		"itemCategoryHash": 18,
		"identifier": "CATEGORY_CURRENCY",
		"visible": false,
		"title": "Currencies",
		"shortTitle": "Currencies",
		"description": "Used to buy new weapons and gear.",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 18,
		"index": 0
	},
	"19": {
		"itemCategoryHash": 19,
		"identifier": "CATEGORY_EMBLEM",
		"visible": false,
		"title": "Emblems",
		"shortTitle": "Emblems",
		"description": "Icons and nameplates.",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 19,
		"index": 0
	},
	"20": {
		"itemCategoryHash": 20,
		"identifier": "CATEGORY_ARMOR",
		"visible": false,
		"title": "Armor",
		"shortTitle": "Armor",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 20,
		"index": 0
	},
	"21": {
		"itemCategoryHash": 21,
		"identifier": "CATEGORY_CLASS_WARLOCK",
		"visible": false,
		"title": "Warlock",
		"shortTitle": "Warlock",
		"description": "Warlock class helmets, chest, arms and legs",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 21,
		"index": 0
	},
	"22": {
		"itemCategoryHash": 22,
		"identifier": "CATEGORY_CLASS_TITAN",
		"visible": false,
		"title": "Titan",
		"shortTitle": "Titan",
		"description": "Titan class helmets, chest, arms and legs",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 22,
		"index": 0
	},
	"23": {
		"itemCategoryHash": 23,
		"identifier": "CATEGORY_CLASS_HUNTER",
		"visible": false,
		"title": "Hunter",
		"shortTitle": "Hunter",
		"description": "Hunter class helmets, chest, arms and legs",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 23,
		"index": 0
	},
	"24": {
		"itemCategoryHash": 24,
		"identifier": "CATEGORY_COMPLETED_BOUNTY",
		"visible": false,
		"title": "",
		"shortTitle": "",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 24,
		"index": 0
	},
	"25": {
		"itemCategoryHash": 25,
		"identifier": "CATEGORY_BOUNTY_REWARD",
		"visible": false,
		"title": "",
		"shortTitle": "",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 25,
		"index": 0
	},
	"26": {
		"itemCategoryHash": 26,
		"identifier": "CATEGORY_BOUNTY",
		"visible": false,
		"title": "Bounties",
		"shortTitle": "Bounties",
		"description": "Vendor missions",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 26,
		"index": 0
	},
	"27": {
		"itemCategoryHash": 27,
		"identifier": "CATEGORY_VANGUARD",
		"visible": false,
		"title": "",
		"shortTitle": "",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 27,
		"index": 0
	},
	"28": {
		"itemCategoryHash": 28,
		"identifier": "CATEGORY_CRUCIBLE",
		"visible": false,
		"title": "",
		"shortTitle": "",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 28,
		"index": 0
	},
	"29": {
		"itemCategoryHash": 29,
		"identifier": "CATEGORY_QUEEN",
		"visible": false,
		"title": "",
		"shortTitle": "",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 29,
		"index": 0
	},
	"30": {
		"itemCategoryHash": 30,
		"identifier": "CATEGORY_IRON_BANNER",
		"visible": false,
		"title": "",
		"shortTitle": "",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 30,
		"index": 0
	},
	"31": {
		"itemCategoryHash": 31,
		"identifier": "CATEGORY_EXOTIC",
		"visible": false,
		"title": "",
		"shortTitle": "",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 31,
		"index": 0
	},
	"32": {
		"itemCategoryHash": 32,
		"identifier": "CATEGORY_MESSAGE",
		"visible": false,
		"title": "",
		"shortTitle": "",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 32,
		"index": 0
	},
	"33": {
		"itemCategoryHash": 33,
		"identifier": "CATEGORY_CRM",
		"visible": false,
		"title": "",
		"shortTitle": "",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 33,
		"index": 0
	},
	"34": {
		"itemCategoryHash": 34,
		"identifier": "CATEGORY_ENGRAM",
		"visible": false,
		"title": "Engrams",
		"shortTitle": "Engrams",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 34,
		"index": 0
	},
	"35": {
		"itemCategoryHash": 35,
		"identifier": "CATEGORY_CONSUMABLE",
		"visible": false,
		"title": "Consumables",
		"shortTitle": "Consumables",
		"description": "Ammo, upgrades and powerups.",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 35,
		"index": 0
	},
	"36": {
		"itemCategoryHash": 36,
		"identifier": "CATEGORY_EXCHANGE_MATERIAL",
		"visible": false,
		"title": "",
		"shortTitle": "",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 36,
		"index": 0
	},
	"37": {
		"itemCategoryHash": 37,
		"identifier": "CATEGORY_MISSION_REWARD",
		"visible": false,
		"title": "",
		"shortTitle": "",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 37,
		"index": 0
	},
	"38": {
		"itemCategoryHash": 38,
		"identifier": "CATEGORY_ARTIFACT",
		"visible": false,
		"title": "Artifact",
		"shortTitle": "Artifact",
		"description": "Relics of the Golden Age.",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 38,
		"index": 0
	},
	"39": {
		"itemCategoryHash": 39,
		"identifier": "CATEGORY_GHOST",
		"visible": false,
		"title": "Ghost",
		"shortTitle": "Ghost",
		"description": "Cosmetic shells for your Ghost.",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 39,
		"index": 0
	},
	"40": {
		"itemCategoryHash": 40,
		"identifier": "CATEGORY_MATERIAL",
		"visible": false,
		"title": "Materials",
		"shortTitle": "Materials",
		"description": "Used to upgrade weapons and gear.",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 40,
		"index": 0
	},
	"41": {
		"itemCategoryHash": 41,
		"identifier": "CATEGORY_SHADER",
		"visible": false,
		"title": "Shaders",
		"shortTitle": "Shaders",
		"description": "Add color and texture to existing armor.",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 41,
		"index": 0
	},
	"42": {
		"itemCategoryHash": 42,
		"identifier": "CATEGORY_SHIP",
		"visible": false,
		"title": "Ships",
		"shortTitle": "Ships",
		"description": "Spacecrafts used to traverse between destinations.",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 42,
		"index": 0
	},
	"43": {
		"itemCategoryHash": 43,
		"identifier": "CATEGORY_VEHICLE",
		"visible": false,
		"title": "Sparrows",
		"shortTitle": "Sparrows",
		"description": "Land vehicles used to quickly traverse a destination.",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 43,
		"index": 0
	},
	"44": {
		"itemCategoryHash": 44,
		"identifier": "CATEGORY_EMOTE",
		"visible": false,
		"title": "Emotes",
		"shortTitle": "Emotes",
		"description": "Strike a pose.",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 44,
		"index": 0
	},
	"45": {
		"itemCategoryHash": 45,
		"identifier": "CATEGORY_ARMOR_HEAD",
		"visible": false,
		"title": "Helmets",
		"shortTitle": "Helmets",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 45,
		"index": 0
	},
	"46": {
		"itemCategoryHash": 46,
		"identifier": "CATEGORY_ARMOR_ARMS",
		"visible": false,
		"title": "Arms",
		"shortTitle": "Arms",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 46,
		"index": 0
	},
	"47": {
		"itemCategoryHash": 47,
		"identifier": "CATEGORY_ARMOR_CHEST",
		"visible": false,
		"title": "Chest",
		"shortTitle": "Chest",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 47,
		"index": 0
	},
	"48": {
		"itemCategoryHash": 48,
		"identifier": "CATEGORY_ARMOR_LEGS",
		"visible": false,
		"title": "Legs",
		"shortTitle": "Legs",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 48,
		"index": 0
	},
	"49": {
		"itemCategoryHash": 49,
		"identifier": "CATEGORY_ARMOR_CLASS",
		"visible": false,
		"title": "Class Items",
		"shortTitle": "Class Items",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 49,
		"index": 0
	},
	"50": {
		"itemCategoryHash": 50,
		"identifier": "CATEGORY_BUILD",
		"visible": false,
		"title": "Subclasses",
		"shortTitle": "Subclasses",
		"description": "Builds for your characters.",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 50,
		"index": 0
	},
	"51": {
		"itemCategoryHash": 51,
		"identifier": "CATEGORY_SHIP_BLUEPRINT",
		"visible": false,
		"title": "###ItemCategories.CATEGORY_SHIP_BLUEPRINT-TITLE###",
		"shortTitle": "###ItemCategories.CATEGORY_SHIP_BLUEPRINT-SHORT_TITLE###",
		"description": "###ItemCategories.CATEGORY_SHIP_BLUEPRINT-DESCRIPTION###",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 51,
		"index": 0
	},
	"52": {
		"itemCategoryHash": 52,
		"identifier": "CATEGORY_INVENTORY",
		"visible": false,
		"title": "Inventory",
		"shortTitle": "Inventory",
		"description": "",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 52,
		"index": 0
	},
	"53": {
		"itemCategoryHash": 53,
		"identifier": "CATEGORY_QUEST",
		"visible": true,
		"title": "Quest",
		"shortTitle": "Quest",
		"description": "Quests that can be completed in Destiny.",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 53,
		"index": 0
	},
	"54": {
		"itemCategoryHash": 54,
		"identifier": "CATEGORY_SWORD",
		"visible": true,
		"title": "Sword",
		"shortTitle": "Sword",
		"description": "Make sure the pointy end faces toward your enemy.",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 54,
		"index": 0
	},
	"55": {
		"itemCategoryHash": 55,
		"identifier": "CATEGORY_MASK",
		"visible": false,
		"title": "Mask",
		"shortTitle": "Mask",
		"description": "(Insert appropriate Jim Carrey quote here)",
		"grantDestinyItemType": 0,
		"grantDestinySubType": 0,
		"grantDestinyClass": 0,
		"hash": 55,
		"index": 0
	}
}