var DestinySpecialEventDefinition = {
	"1": {
		"eventHash": 1,
		"eventIdentifier": "SPECIAL_EVENT_QUEEN",
		"backgroundImageWeb": "TEST.JPG",
		"title": "QUEEN'S WRATH",
		"subtitle": "LIMITED TIME EVENT",
		"link": "",
		"icon": "",
		"showNagMessage": true,
		"progressionHash": 452808717,
		"vendorHash": 3039124256,
		"factionHash": 807090922,
		"activeUnlockValueHash": 0,
		"bountyHashes": [],
		"questHashes": [],
		"hash": 1,
		"index": 0
	},
	"2": {
		"eventHash": 2,
		"eventIdentifier": "SPECIAL_EVENT_IRON_BANNER",
		"backgroundImageWeb": "TEST.JPG",
		"title": "IRON BANNER",
		"subtitle": "LIMITED TIME EVENT",
		"link": "http://www.bungie.net/en/Event/IronBanner",
		"icon": "/img/destiny_content/events/ib_icon.png",
		"showNagMessage": true,
		"progressionHash": 2161005788,
		"vendorHash": 242140165,
		"factionHash": 2161005788,
		"backgroundImageMobile": "/img/destiny_content/events/ib_mobile.jpg",
		"activeUnlockValueHash": 0,
		"bountyHashes": [],
		"questHashes": [],
		"hash": 2,
		"index": 0
	},
	"3": {
		"eventHash": 3,
		"eventIdentifier": "SPECIAL_EVENT_VEHICLES",
		"backgroundImageWeb": "TEST.JPG",
		"title": "Combined Arms",
		"subtitle": "LIMITED TIME EVENT",
		"link": "",
		"icon": "",
		"showNagMessage": false,
		"progressionHash": 0,
		"vendorHash": 0,
		"factionHash": 0,
		"activeUnlockValueHash": 0,
		"bountyHashes": [],
		"questHashes": [],
		"hash": 3,
		"index": 0
	},
	"4": {
		"eventHash": 4,
		"eventIdentifier": "SPECIAL_EVENT_SALVAGE",
		"backgroundImageWeb": "TEST.JPG",
		"title": "Salvage",
		"subtitle": "LIMITED TIME EVENT",
		"link": "",
		"icon": "",
		"showNagMessage": false,
		"progressionHash": 0,
		"vendorHash": 0,
		"factionHash": 0,
		"activeUnlockValueHash": 0,
		"bountyHashes": [],
		"questHashes": [],
		"hash": 4,
		"index": 0
	},
	"5": {
		"eventHash": 5,
		"eventIdentifier": "SPECIAL_EVENT_BLACK_MARKET",
		"backgroundImageWeb": "TEST.JPG",
		"title": "XÛR has arrived... for now...",
		"subtitle": "",
		"link": "",
		"icon": "/img/destiny_content/events/xur_icon.png",
		"showNagMessage": true,
		"progressionHash": 0,
		"vendorHash": 2796397637,
		"factionHash": 0,
		"backgroundImageMobile": "/img/destiny_content/events/xur_mobile.jpg",
		"activeUnlockValueHash": 0,
		"bountyHashes": [],
		"questHashes": [],
		"hash": 5,
		"index": 0
	},
	"6": {
		"eventHash": 6,
		"eventIdentifier": "SPECIAL_EVENT_SRL",
		"backgroundImageWeb": "TEST.JPG",
		"title": "Sparrow Racing",
		"subtitle": "Limited Time Event",
		"link": "http://www.bungie.net/en/pub/SparrowRacing?tootyourown=horn",
		"icon": "",
		"showNagMessage": false,
		"progressionHash": 2763619072,
		"vendorHash": 459708109,
		"factionHash": 2763619072,
		"backgroundImageMobile": "/img/destiny_content/events/srl_mobile.jpg",
		"activeUnlockValueHash": 0,
		"bountyHashes": [
			4275602358,
			4275602359,
			4275602356,
			4275602357,
			4275602354,
			4275602355,
			4275602352,
			4275602353,
			4275602366,
			4275602367,
			3856095525,
			3856095524
		],
		"questHashes": [
			22457969
		],
		"hash": 6,
		"index": 0
	}
}