var DestinyActivityTypeDefinition = {
	"39921727": {
		"activityTypeHash": 39921727,
		"identifier": "ACTIVITY_TYPE_PVP_ELIMINATION",
		"activityTypeName": "Elimination",
		"activityTypeDescription": "Small-team tactics. Wipe out enemies. Revive teammates.",
		"icon": "/img/theme/destiny/icons/pvp_gametype_elimination.v2.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 65,
		"statGroup": "elimination",
		"friendlyUrlId": "elimination",
		"hash": 39921727,
		"index": 0
	},
	"55476966": {
		"activityTypeHash": 55476966,
		"identifier": "PVP_FFA_HARDCORE",
		"activityTypeName": "Inferno Rumble",
		"icon": "/common/destiny_content/icons/28aac181ef13a5395c5f9151c6c4b79e.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 1,
		"hash": 55476966,
		"index": 0
	},
	"147238405": {
		"activityTypeHash": 147238405,
		"identifier": "ACTIVITY_TYPE_STORY_FEATURED",
		"activityTypeName": "Story",
		"activityTypeDescription": "Embark on adventures alone or with a fireteam to push back the Darkness and reclaim our lost worlds.",
		"icon": "/img/theme/destiny/icons/node_story_featured.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/story.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/story.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/story.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/story.png",
		"order": 1,
		"hash": 147238405,
		"index": 0
	},
	"308891298": {
		"activityTypeHash": 308891298,
		"activityTypeName": "Iron Banner",
		"activityTypeDescription": "The Lords of Iron summon Guardians to test themselves and their peers in the Crucible.",
		"icon": "/common/destiny_content/icons/0ee91b79ba1366243832cf810afc3b75.jpg",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 0,
		"hash": 308891298,
		"index": 0
	},
	"328502994": {
		"activityTypeHash": 328502994,
		"identifier": "STORY_SOLO",
		"activityTypeName": "Story",
		"activityTypeDescription": "Embark on adventures alone or with a fireteam to push back the Darkness and reclaim our lost worlds.",
		"icon": "/common/destiny_content/icons/42bcde5122ba7c11443079e4fd8f1dfd.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/story.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/story.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/story.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/story.png",
		"order": 1,
		"hash": 328502994,
		"index": 0
	},
	"575572995": {
		"activityTypeHash": 575572995,
		"identifier": "ACTIVITY_TYPE_NIGHTFALL",
		"activityTypeName": "Strike",
		"activityTypeDescription": "Join a fireteam of three and face the most feared minions of the Darkness.",
		"icon": "/common/destiny_content/icons/180e38a661408ba17d39beac44232b42.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/strikes.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/strikes.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/strikes.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/strikes.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/strikes.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/strikes.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/strikes.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/strikes.png",
		"order": 1,
		"statGroup": "nightfall",
		"friendlyUrlId": "nightfall",
		"hash": 575572995,
		"index": 0
	},
	"579151588": {
		"activityTypeHash": 579151588,
		"identifier": "PVP_ZONE_CONTROL",
		"activityTypeName": "Zone Control",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/icon_pvp_95758a0126585ca7a5344b1424aaec7c.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 45,
		"statGroup": "zoneControl",
		"friendlyUrlId": "zoneControl",
		"hash": 579151588,
		"index": 0
	},
	"680256650": {
		"activityTypeHash": 680256650,
		"identifier": "ARENA",
		"activityTypeName": "Prison of Elders",
		"icon": "/common/destiny_content/icons/8efcf7a0ef0b531113c3e20aba02a832.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"order": 1,
		"hash": 680256650,
		"index": 0
	},
	"736189348": {
		"activityTypeHash": 736189348,
		"identifier": "ACTIVITY_TYPE_PVP_PLAYLIST_TOURNAMENT",
		"activityTypeName": "Trials of Osiris",
		"activityTypeDescription": "You have caught the eye of Osiris. Venture to Mercury and prove yourself as one of the Crucible's elite.",
		"icon": "/img/theme/destiny/icons/osiris_diamond.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 150,
		"statGroup": "trialsOfOsiris",
		"friendlyUrlId": "trialsofosiris",
		"hash": 736189348,
		"index": 0
	},
	"837773392": {
		"activityTypeHash": 837773392,
		"identifier": "RAID_MOON1",
		"activityTypeName": "Raid",
		"activityTypeDescription": "Form a fireteam of six and brave the strange and powerful realms of our enemies.",
		"icon": "/common/destiny_content/icons/1dabf4d35cf3ba13e3b3e8e48ac91d0c.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/raids.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/raids.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/raids.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/raids.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/raids.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/raids.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/raids.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/raids.png",
		"order": 1,
		"hash": 837773392,
		"index": 0
	},
	"976536573": {
		"activityTypeHash": 976536573,
		"identifier": "PVP_MAYHEM_RUMBLE",
		"activityTypeName": "Mayhem Rumble",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/28aac181ef13a5395c5f9151c6c4b79e.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 48,
		"statGroup": "mayhemRumble",
		"friendlyUrlId": "mayhemrumble",
		"hash": 976536573,
		"index": 0
	},
	"1030667770": {
		"activityTypeHash": 1030667770,
		"identifier": "PVP_FFA_ARTIFACT",
		"activityTypeName": "Arsenal",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/335e7a98645c065a74813debe57fdc1e.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 1,
		"hash": 1030667770,
		"index": 0
	},
	"1037283719": {
		"activityTypeHash": 1037283719,
		"identifier": "ACTIVITY_TYPE_STORY_QUEEN",
		"activityTypeName": "Story Challenge",
		"activityTypeDescription": "The Queen and the City share mutual enemies. Usually. Help the Awoken of the Reef and earn her favor.",
		"icon": "/img/theme/destiny/icons/node_queen.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/story.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/story.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/story.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/story.png",
		"order": 1,
		"hash": 1037283719,
		"index": 0
	},
	"1066759414": {
		"activityTypeHash": 1066759414,
		"identifier": "PVP_RACING",
		"activityTypeName": "SRL",
		"activityTypeDescription": "Ride fast. Be brave. Become a champion.",
		"icon": "/common/destiny_content/icons/67bcfef32e0459c6d2814865fd625ad2.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 49,
		"statGroup": "racing",
		"friendlyUrlId": "racing",
		"hash": 1066759414,
		"index": 0
	},
	"1129694690": {
		"activityTypeHash": 1129694690,
		"identifier": "ACTIVITY_TYPE_TIGER_AD",
		"activityTypeName": "It's an advertisement!",
		"activityTypeDescription": "",
		"icon": "/common/destiny_content/icons/42bcde5122ba7c11443079e4fd8f1dfd.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"order": 1,
		"hash": 1129694690,
		"index": 0
	},
	"1299744814": {
		"activityTypeHash": 1299744814,
		"identifier": "STORY_CINEMATIC",
		"activityTypeName": "Story",
		"activityTypeDescription": "Embark on adventures alone or with a fireteam to push back the Darkness and reclaim our lost worlds.",
		"icon": "/common/destiny_content/icons/42bcde5122ba7c11443079e4fd8f1dfd.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/story.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/story.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/story.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/story.png",
		"order": 1,
		"hash": 1299744814,
		"index": 0
	},
	"1337970376": {
		"activityTypeHash": 1337970376,
		"identifier": "ACTIVITY_TYPE_PVP_PLAYLIST_IRON_BANNER",
		"activityTypeName": "Iron Banner",
		"activityTypeDescription": "The Lords of Iron summon Guardians to test themselves and their peers in the Crucible.",
		"icon": "/img/theme/destiny/icons/node_pvp_iron_banner.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 100,
		"statGroup": "ironBanner",
		"friendlyUrlId": "ironBanner",
		"hash": 1337970376,
		"index": 0
	},
	"1526862764": {
		"activityTypeHash": 1526862764,
		"identifier": "PVP_TEAM_HARDCORE",
		"activityTypeName": "Inferno Clash",
		"icon": "/common/destiny_content/icons/7f41a2e3f4a231d685a62ce2ccf060ba.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 1,
		"hash": 1526862764,
		"index": 0
	},
	"1533445734": {
		"activityTypeHash": 1533445734,
		"identifier": "PVP_DOUBLES",
		"activityTypeName": "Doubles",
		"activityTypeDescription": "Small-team tactics. Revive teammates.",
		"icon": "/common/destiny_content/icons/icon_pvp_fcef5a437dc31c4478edb531d1e9093f.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 60,
		"hash": 1533445734,
		"index": 0
	},
	"1589650888": {
		"activityTypeHash": 1589650888,
		"identifier": "ACTIVITY_TYPE_SOCIAL",
		"activityTypeName": "Social",
		"activityTypeDescription": "Meet other Guardians as they prepare for new adventures.",
		"icon": "/common/destiny_content/icons/4e7327a9d96eeb2c79306339125109b6.png",
		"order": 1,
		"hash": 1589650888,
		"index": 0
	},
	"1646825171": {
		"activityTypeHash": 1646825171,
		"identifier": "PVP_3V3_HARDCORE",
		"activityTypeName": "Inferno Skirmish",
		"icon": "/common/destiny_content/icons/1843c2bac315e8c84ebfb693ec5e5492.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 1,
		"hash": 1646825171,
		"index": 0
	},
	"1686739444": {
		"activityTypeHash": 1686739444,
		"identifier": "ACTIVITY_TYPE_STORY",
		"activityTypeName": "Story",
		"activityTypeDescription": "Embark on adventures alone or with a fireteam to push back the Darkness and reclaim our lost worlds.",
		"icon": "/common/destiny_content/icons/42bcde5122ba7c11443079e4fd8f1dfd.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/story.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/story.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/story.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/story.png",
		"order": 1,
		"hash": 1686739444,
		"index": 0
	},
	"1801258597": {
		"activityTypeHash": 1801258597,
		"identifier": "QUEST",
		"activityTypeName": "Quest",
		"activityTypeDescription": "Embark on a continuous journey for those who need the help of the Guardians.",
		"icon": "/common/destiny_content/icons/850c5a02e5a8e332270f7744bdc2793c.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"order": 1,
		"hash": 1801258597,
		"index": 0
	},
	"1925914835": {
		"activityTypeHash": 1925914835,
		"identifier": "DARE",
		"icon": "/img/misc/missing_icon.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"order": 1,
		"hash": 1925914835,
		"index": 0
	},
	"1957882444": {
		"activityTypeHash": 1957882444,
		"identifier": "ACTIVITY_TYPE_DLC_AD",
		"activityTypeName": "A new expansion is available!",
		"activityTypeDescription": "",
		"icon": "/common/destiny_content/icons/42bcde5122ba7c11443079e4fd8f1dfd.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"order": 1,
		"hash": 1957882444,
		"index": 0
	},
	"2043403989": {
		"activityTypeHash": 2043403989,
		"identifier": "ACTIVITY_TYPE_RAID",
		"activityTypeName": "Raid",
		"activityTypeDescription": "Form a fireteam of six and brave the strange and powerful realms of our enemies.",
		"icon": "/common/destiny_content/icons/1dabf4d35cf3ba13e3b3e8e48ac91d0c.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/raids.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/raids.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/raids.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/raids.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/raids.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/raids.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/raids.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/raids.png",
		"order": 1,
		"hash": 2043403989,
		"index": 0
	},
	"2127351241": {
		"activityTypeHash": 2127351241,
		"identifier": "ACTIVITY_TYPE_PVP_LOCK",
		"activityTypeName": "Salvage",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/icon_pvp_43319e992dcbb18bf0936a2fab0c946a.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 60,
		"statGroup": "lockdown",
		"friendlyUrlId": "salvage",
		"hash": 2127351241,
		"index": 0
	},
	"2201105581": {
		"activityTypeHash": 2201105581,
		"identifier": "CREDITS",
		"activityTypeName": "Story",
		"activityTypeDescription": "Embark on adventures alone or with a fireteam to push back the Darkness and reclaim our lost worlds.",
		"icon": "/common/destiny_content/icons/42bcde5122ba7c11443079e4fd8f1dfd.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"order": 1,
		"hash": 2201105581,
		"index": 0
	},
	"2691931425": {
		"activityTypeHash": 2691931425,
		"identifier": "PVP_DOM_HARDCORE",
		"activityTypeName": "Inferno Control",
		"icon": "/common/destiny_content/icons/9950163a589a83493641fe05aae2b59e.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 1,
		"hash": 2691931425,
		"index": 0
	},
	"2833173037": {
		"activityTypeHash": 2833173037,
		"identifier": "PVP_SINGULARITY",
		"activityTypeName": "Rift",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/icon_pvp_b6f9fe6fcff889bbb26025643266f403.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 43,
		"statGroup": "rift",
		"friendlyUrlId": "rift",
		"hash": 2833173037,
		"index": 0
	},
	"2881466965": {
		"activityTypeHash": 2881466965,
		"identifier": "QUEST_SOLO",
		"activityTypeName": "Quest",
		"activityTypeDescription": "Embark on a continuous journey for those who need the help of the Guardians.",
		"icon": "/common/destiny_content/icons/850c5a02e5a8e332270f7744bdc2793c.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"order": 1,
		"hash": 2881466965,
		"index": 0
	},
	"2889152536": {
		"activityTypeHash": 2889152536,
		"identifier": "ACTIVITY_TYPE_STRIKE_PLAYLIST",
		"activityTypeName": "Strike",
		"activityTypeDescription": "Join a fireteam of three and face the most feared minions of the Darkness.",
		"icon": "/common/destiny_content/icons/180e38a661408ba17d39beac44232b42.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/strikes.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/strikes.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/strikes.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/strikes.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/strikes.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/strikes.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/strikes.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/strikes.png",
		"order": 1,
		"hash": 2889152536,
		"index": 0
	},
	"2942016862": {
		"activityTypeHash": 2942016862,
		"identifier": "ACTIVITY_TYPE_PVP_PLAYLIST",
		"activityTypeName": "The Crucible",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/icon_pvp_b6b020f7fc23b66c5e885707e950a63b.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": -1,
		"hash": 2942016862,
		"index": 0
	},
	"3195758403": {
		"activityTypeHash": 3195758403,
		"identifier": "MOCK",
		"activityTypeName": "It's an advertisement!",
		"activityTypeDescription": "",
		"icon": "/common/destiny_content/icons/42bcde5122ba7c11443079e4fd8f1dfd.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"order": 1,
		"hash": 3195758403,
		"index": 0
	},
	"3323301749": {
		"activityTypeHash": 3323301749,
		"identifier": "PVP_MAYHEM_CLASH",
		"activityTypeName": "Mayhem Clash",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/7f41a2e3f4a231d685a62ce2ccf060ba.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 47,
		"statGroup": "mayhemClash",
		"friendlyUrlId": "mayhemclash",
		"hash": 3323301749,
		"index": 0
	},
	"3409618559": {
		"activityTypeHash": 3409618559,
		"identifier": "ACTIVITY_TYPE_PVP_VEHICLES",
		"activityTypeName": "Combined Arms",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/icon_pvp_7cc4e800926682a3afaf480909906013.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 40,
		"statGroup": "combined_arms",
		"friendlyUrlId": "combined_arms",
		"hash": 3409618559,
		"index": 0
	},
	"3432675002": {
		"activityTypeHash": 3432675002,
		"identifier": "PVP_PLAYLIST_IRON_BANNER_DM_TEAM_LARGE",
		"activityTypeName": "Iron Banner",
		"icon": "/common/destiny_content/icons/0ee91b79ba1366243832cf810afc3b75.jpg",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 1,
		"hash": 3432675002,
		"index": 0
	},
	"3433065842": {
		"activityTypeHash": 3433065842,
		"activityTypeName": "Inferno Doubles",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/1843c2bac315e8c84ebfb693ec5e5492.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 0,
		"hash": 3433065842,
		"index": 0
	},
	"3497767639": {
		"activityTypeHash": 3497767639,
		"identifier": "ACTIVITY_TYPE_EXPLORE",
		"activityTypeName": "Patrol",
		"activityTypeDescription": "Wander the frontier. Search the ruins of the Golden Age, claim vital supplies, and hunt down our enemies wherever they dare trespass.",
		"icon": "/common/destiny_content/icons/db10d2b0b8344ed08f4e41222b99f907.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/patrols.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/patrols.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/patrols.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/patrols.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/patrols.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/patrols.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/patrols.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/patrols.png",
		"order": 1,
		"hash": 3497767639,
		"index": 0
	},
	"3582414910": {
		"activityTypeHash": 3582414910,
		"activityTypeName": "Inferno 6v6",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/d19b816728b16eec2cd07987e3ba3bfc.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 0,
		"hash": 3582414910,
		"index": 0
	},
	"3597531865": {
		"activityTypeHash": 3597531865,
		"activityTypeName": "Classic Free-For-All",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/d19b816728b16eec2cd07987e3ba3bfc.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 0,
		"hash": 3597531865,
		"index": 0
	},
	"3614615911": {
		"activityTypeHash": 3614615911,
		"identifier": "ACTIVITY_TYPE_PVP_TEAM",
		"activityTypeName": "Clash",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/icon_pvp_d0a189071d8eb5d009f4252bef78b551.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 20,
		"statGroup": "team",
		"friendlyUrlId": "clash",
		"hash": 3614615911,
		"index": 0
	},
	"3616808722": {
		"activityTypeHash": 3616808722,
		"activityTypeName": "Inferno 3v3",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/d19b816728b16eec2cd07987e3ba3bfc.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 0,
		"hash": 3616808722,
		"index": 0
	},
	"3695721985": {
		"activityTypeHash": 3695721985,
		"identifier": "ACTIVITY_TYPE_PVP_FFA",
		"activityTypeName": "Rumble",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/icon_pvp_7f4c923551a74315df3dcd493291bcf4.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 30,
		"statGroup": "freeForAll",
		"friendlyUrlId": "rumble",
		"hash": 3695721985,
		"index": 0
	},
	"3705723572": {
		"activityTypeHash": 3705723572,
		"identifier": "ARENA_CHALLENGE",
		"activityTypeName": "Challenge of the Elders",
		"icon": "/common/destiny_content/icons/8efcf7a0ef0b531113c3e20aba02a832.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/ministory.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/ministory.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/ministory.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/ministory.png",
		"order": 1,
		"hash": 3705723572,
		"index": 0
	},
	"3828541881": {
		"activityTypeHash": 3828541881,
		"activityTypeName": "Crimson Doubles",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/61d6eb3df0060df883605cd9510e5ef9.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 0,
		"hash": 3828541881,
		"index": 0
	},
	"3846426416": {
		"activityTypeHash": 3846426416,
		"identifier": "ACTIVITY_TYPE_PVP_DOM",
		"activityTypeName": "Control",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/icon_pvp_80209e5d3802747a308bbdbe12bee676.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 10,
		"statGroup": "control",
		"friendlyUrlId": "control",
		"hash": 3846426416,
		"index": 0
	},
	"3852968078": {
		"activityTypeHash": 3852968078,
		"activityTypeName": "Classic 6v6",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/d19b816728b16eec2cd07987e3ba3bfc.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 0,
		"hash": 3852968078,
		"index": 0
	},
	"3887258850": {
		"activityTypeHash": 3887258850,
		"activityTypeName": "Classic 3v3",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/d19b816728b16eec2cd07987e3ba3bfc.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 0,
		"hash": 3887258850,
		"index": 0
	},
	"3923114990": {
		"activityTypeHash": 3923114990,
		"identifier": "PVP_LOCK_HARDCORE",
		"activityTypeName": "Inferno Salvage",
		"icon": "/common/destiny_content/icons/6f8cd4d18891e5b4b3c8abe022042aa0.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 1,
		"hash": 3923114990,
		"index": 0
	},
	"3957072814": {
		"activityTypeHash": 3957072814,
		"identifier": "PVP_2V2",
		"activityTypeName": "Doubles",
		"icon": "/common/destiny_content/icons/icon_pvp_fcef5a437dc31c4478edb531d1e9093f.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 60,
		"statGroup": "doubles",
		"friendlyUrlId": "doublesskirmish",
		"hash": 3957072814,
		"index": 0
	},
	"3990775146": {
		"activityTypeHash": 3990775146,
		"identifier": "ACTIVITY_TYPE_PVP_3V3",
		"activityTypeName": "Skirmish",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/icon_pvp_861c57fe187f7ab2743a647b73dd1973.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 50,
		"statGroup": "threeVsThree",
		"friendlyUrlId": "skirmish",
		"hash": 3990775146,
		"index": 0
	},
	"4013076195": {
		"activityTypeHash": 4013076195,
		"activityTypeName": "Freelance 3v3",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/d19b816728b16eec2cd07987e3ba3bfc.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 0,
		"hash": 4013076195,
		"index": 0
	},
	"4047366879": {
		"activityTypeHash": 4047366879,
		"activityTypeName": "Freelance 6v6",
		"activityTypeDescription": "Face your fellow Guardians in open combat. Prove your worth, and you will be rewarded.",
		"icon": "/common/destiny_content/icons/d19b816728b16eec2cd07987e3ba3bfc.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/crucible.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/crucible.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/crucible.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/crucible.png",
		"order": 0,
		"hash": 4047366879,
		"index": 0
	},
	"4110605575": {
		"activityTypeHash": 4110605575,
		"identifier": "ACTIVITY_TYPE_STRIKE",
		"activityTypeName": "Strike",
		"activityTypeDescription": "Join a fireteam of three and face the most feared minions of the Darkness.",
		"icon": "/common/destiny_content/icons/180e38a661408ba17d39beac44232b42.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/strikes.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/strikes.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/strikes.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/strikes.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/strikes.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/strikes.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/strikes.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/strikes.png",
		"order": 1,
		"hash": 4110605575,
		"index": 0
	},
	"4164571395": {
		"activityTypeHash": 4164571395,
		"identifier": "STRIKE_WEEKLY",
		"activityTypeName": "Strike",
		"activityTypeDescription": "Join a fireteam of three and face the most feared minions of the Darkness.",
		"icon": "/img/theme/destiny/icons/node_strike_featured.png",
		"activeBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/strikes.png",
		"completedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/strikes.png",
		"hiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/strikes.png",
		"tooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/strikes.png",
		"enlargedActiveBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Active/strikes.png",
		"enlargedCompletedBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Completed/strikes.png",
		"enlargedHiddenOverrideVirtualPath": "/img/destiny_content/ActivityTypeBackground/Hidden/strikes.png",
		"enlargedTooltipBackgroundVirtualPath": "/img/destiny_content/ActivityTypeBackground/Tooltip/strikes.png",
		"order": 1,
		"hash": 4164571395,
		"index": 0
	}
}